### ISSUE TITLE
empty file wurst/ecoinvent/__init___.py leads to error: "ImportError: cannot import name 'ECOINVENT_ORDERED_GEO' from 'wurst.ecoinvent'"

### ISSUE THREAD

**Issue by simb-sdu** [polca/wurst#26]
Trying to execute the [marginal mixes wurst notebook example](https://github.com/IndEcol/wurst-examples/blob/master/marginal-mixes/marginal-mixes.ipynb) but got an error 
ImportError: cannot import name 'ECOINVENT_ORDERED_GEO' from 'wurst.ecoinvent'
 
I see also that [others](https://github.com/IndEcol/wurst-examples/issues/2) have encountered the same issue. I contacted Laurant Vandepaer, who has no solution.

It seems that the wurst/ecoinvent/__init___.py file is empty as per 28 sept 2017. I found the [previuos file version](https://github.com/polca/wurst/blob/637ea9994b15bee63f8c303893c903eadd62204d/wurst/ecoinvent/__init__.py) in the commit history. copied the lines of code into my local __init___.py file to resolve the issue.

I wanted to share this workaround in case others might be interested. I am new to github, and don't know how to contribute this? hence i made this post. Is it correct understood that I should make a "pull request" for the commit of 28 sept 2017, which deleted all lines of code from the __init___.py file? I cant figure out how to do this :-)

Best regards, Simon

**Comment by romainsacchi** [comment]
Removing the corresponding cells in the notebook should address this issue.
