### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by nikhilsampathrao** [polca/wurst#36]
Hello, Iam trying to exclude the activity. want to read single activity so. Iam trying w.exclude  code but iam getting attribute error.
also i have tried considering w. doesnt_contain_any but no result error occurs as shown in the attachetment.
can any one please help regrading my code  
![image](https://github.com/user-attachments/assets/b2eef7d1-15fe-410d-b66e-b2dafc89e66f).

![image](https://github.com/user-attachments/assets/f739ea1a-ae48-44b4-9bc3-9d152e139734)

**Comment by romainsacchi** [comment]
Hi @nikhilsampathrao, `equals`, `exclude`, etc. are functions of the `wurst.searching` module, not `wurst`.
See https://github.com/polca/wurst/blob/main/wurst/searching.py
